### PR TITLE
Created DE.json

### PR DESCRIPTION
**Pull request by Razortide**
I was unsure if this will work to accept two values:

"npcImporter.parser.SpecialAbilities": "Spezialfähigkeiten|Besondere Merkmale",

Apart from that, this should work.

Sorry if the pull request has been done the wrong way - first time I try that.

### CODE REVIEW

**Comment by arnonram** [comment]
@Razortide Thanks a lot for this :)

I'm unsure as well about the special abilities and if pipe works. I'll look into it before merging

**Comment by Razortide** [comment]
Once question @arnonram, in German publications it is not dX but WX. I am unsure if I translated something like this. Would it be a bit issue to add it?

**Comment by arnonram** [comment]
**re: pipe** => right you are... but it seems that it's not in use anywhere... and it's not working properly... need to look into it

**re: dX -> WX** => i'll need to look into as well

**Comment by Razortide** [comment]
Thank you for checking. Is there anything I need to do?

**Comment by arnonram** [comment]
no... but i want to wait with this merge until i find a good solution

**Comment by Razortide** [comment]
So "Besondere Merkmale" is old format - Spezialfähigkeiten is SWADE speech :-)

**Comment by arnonram** [comment]
@Razortide 
hmm... i've always said that NPC importer supports swade, so perhaps for the meantime, we keep only Spezialfähigkeiten?
i'll keep #100 open and think about it, but there will be no great rush for it at the moment

What do you think?

**Comment by Razortide** [comment]
I totally agree!

**Pull request closed without merging**
